name: places_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.1.4
homepage: https://github.com/drexsoftorg/places_picker
issue_tracker: https://github.com/drexsoftorg/places_picker/issues
repository: https://github.com/drexsoftorg/places_picker

platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: 2.12.1
  geolocator: 13.0.1
  permission_handler: 12.0.0+1
  provider: ^6.0.5
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_api_headers: 4.4.2
  tuple: 2.0.2
  http: ^0.13.5
  cirilica: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/places_picker/assets/dark_map_style.json
